catalog/urls.py
from django.urls import path
from .views import CategoryDetailView, CategoryListView, CassetteBrandListView, CassetteBrandDetail, \
    CassetteCatalogBrandDetailView, TechnologyListView, CassetteDetailView, CassetteCreateView, CassetteUpdateView

app_name = 'catalog'

urlpatterns = [
    path('', CategoryListView.as_view(), name='catalog-list'),
    path('category/<slug>/<brand_slug>/', CassetteCatalogBrandDetailView.as_view(), name='catalog-brand-cassette-list'),
    path('category/<slug>/', CategoryDetailView.as_view(), name='catalog-detail'),
    path('brands/', CassetteBrandListView.as_view(), name='brand-list'),
    path('brands/<slug>/', CassetteBrandDetail.as_view(), name='brand-detail'),
    path('technology/', TechnologyListView.as_view(), name='technologies'),
    path('cassettes/<int:id>/', CassetteDetailView.as_view(), name='cassette'),
    path('cassettes/add/', CassetteCreateView.as_view(), name='cassette_create'),
    path('cassettes/<int:id>/update/', CassetteUpdateView.as_view(), name='cassette_update'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import homepage

app_name = 'core'

urlpatterns = [
    path('', homepage, name='home-page'),
]

kassets/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _

from kassets import settings
from users.views import GoogleSignInView

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('auth/', include('users.urls')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
    path('catalog/', include('catalog.urls')), path('', include('core.urls')),
    path('lists/', include('collection_management.urls'))
)

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


admin.site.index_title = _('Site Content Management')
admin.site.site_header = _('Tape Collector Administration')
admin.site.site_title = _('Tape Collector administration')

users/urls.py
# Импортируем из приложения django.contrib.auth нужный view-класс
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetView, PasswordChangeView, \
    PasswordChangeDoneView
from django.urls import path
from . import views
from .views import Profile, ProfileUpdate

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_change/', PasswordChangeView.as_view(template_name='users/edit-password.html'),
         name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/edit-password-done.html'),
         name='password_change_done'),
    path('profile/', Profile.as_view(), name='profile'),
    path('profile-update/', ProfileUpdate.as_view(), name='profile-update'),
    path('collectors/', views.Collectors.as_view(), name='collectors'),
    path('collector/<int:id>/', views.Collector.as_view(), name='collector'),
]

catalog/models.py
import random
import string
import uuid
from django.db import models
from django.db.models import F, Min, Max
from django.urls import reverse
from django.utils.html import mark_safe
from django.utils.translation import gettext_lazy as _

from pytils.translit import slugify

from core.models import Country
from users.models import Country, User


def title_slugify(model, title):
    slug = slugify(title)
    if model.objects.filter(slug=slug).exists():
        letters = string.ascii_lowercase
        slug = slug + '-' + ''.join(random.choice(letters) for _ in range(3))
    return slug[:50]


class PublishModelManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=True)


class BaseModel(models.Model):
    """Базовая модель"""
    title = models.CharField(max_length=255, unique=True, verbose_name=_('title'))
    slug = models.SlugField(unique=True, blank=True, verbose_name=_('Url/Slug'))
    is_published = models.BooleanField(default=True, verbose_name=_('Publish'))
    created = models.DateTimeField(auto_now=False, auto_now_add=True,
                                   verbose_name=_('Date of created'))
    updated = models.DateTimeField(auto_now=True, auto_now_add=False,
                                   verbose_name=_('Date of updated'))

    objects = models.Manager()
    published_objects = PublishModelManager()

    class Meta:
        abstract = True
        ordering = ('title', )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # self.slug = slugify(self.title)
        self.slug = title_slugify(self.__class__, self.title)
        super().save(*args, **kwargs)


class Category(BaseModel):
    """Модель категории"""
    AUDIO = 'audio'
    VIDEO = 'video'
    CATEGORY_TYPE = ((AUDIO, _('Audio')), (VIDEO, _('Video')),)
    type = models.CharField(max_length=5, choices=CATEGORY_TYPE, default=AUDIO)
    image = models.ImageField(upload_to='category', blank=True)
    logo = models.ImageField(upload_to='category_logo', blank=True)
    description = models.TextField(blank=True)
    brands = models.ManyToManyField('CassetteBrand', related_name='categories', blank=True, verbose_name=_('Brands'))
    is_published_to_home = models.BooleanField(default=False, verbose_name=_('Publish to home page'))
    display_order = models.IntegerField(blank=True, null=True, verbose_name=_('display order'))

    def cassettes_count(self):
        """Считаем количество кассет в категории"""
        return Cassette.objects.filter(brand__categories__slug=self.slug).count()

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ('display_order', 'type', 'title')



class CassetteBrand(BaseModel):
    """Модель бренда"""
    country = models.ForeignKey(Country, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('country'))
    description = models.TextField(blank=True, verbose_name=_('description'))
    image = models.ImageField(upload_to='brands', blank=True, verbose_name=_('image'))

    def cassette_year(self):
        """Вычисляем минимальный и максимальный год кассет в данном бренде"""
        year_period = Cassette.objects.filter(brand=self).aggregate(min=Min('year_release'), max=Max('year_release'))
        return year_period

    def admin_preview(self):
        return mark_safe(
            f'<img src = "{self.image.url}" width = "200"/>')
    admin_preview.short_description = _('image preview')

    def admin_list_preview(self):
        if self.image:
            return mark_safe(
                f'<img src = "{self.image.url}" width = "50"/>')

    admin_list_preview.short_description = _('image')

    class Meta:
        verbose_name = _('brand')
        verbose_name_plural = _('brands')
        ordering = ('title',)




class CassetteModel(BaseModel):
    """Модель модели кассеты"""
    title = models.CharField(max_length=255, unique=False, verbose_name=_('title'))
    brand = models.ForeignKey(CassetteBrand, on_delete=models.PROTECT, verbose_name=_('brand'))
    description = models.TextField(blank=True, verbose_name=_('description'))

    class Meta:
        verbose_name = _('Model')
        verbose_name_plural = _('Models')
        ordering = ('title',)

    def __str__(self):
        return f'{self.title} ({self.brand})'


class CassetteType(BaseModel):
    """Модель типа кассеты"""
    class Meta:
        verbose_name = _('Type')
        verbose_name_plural = _('Types')
        ordering = ('title',)



class CassetteTechnology(BaseModel):
    """Модель технологии кассеты"""
    class Meta:
        verbose_name = _('Technology')
        verbose_name_plural = _('Technologies')
        ordering = ('title',)


class CassetteManufacturer(BaseModel):
    """Модель производителя кассеты"""
    class Meta:
        verbose_name = _('Manufacturer')
        verbose_name_plural = _('Manufacturers')
        ordering = ('title',)


class CassetteSeries(BaseModel):
    """Модель серии кассеты"""
    class Meta:
        verbose_name = _('Series')
        verbose_name_plural = _('Series')
        ordering = ('title',)


class CassetteSort(BaseModel):
    """Модель серии кассеты"""
    class Meta:
        verbose_name = _('sort')
        verbose_name_plural = _('sorts')
        ordering = ('title',)


class CassetteCollection(BaseModel):
    """Модель коллекции"""
    class Meta:
        verbose_name = _('Collection')
        verbose_name_plural = _('Collections')
        ordering = ('title',)


class CassetteTapeLength(models.Model):
    """Модель длины ленты"""
    tape_length = models.CharField(max_length=32,
                                   verbose_name=_('tape length'))

    class Meta:
        verbose_name = _('tape length')
        verbose_name_plural = _('tape lengtes')
        ordering = ('tape_length',)

    def __str__(self):
        return self.tape_length


class CassettePrice(models.Model):
    """Различные варианты цены в зависимости от состояния"""
    poor = models.IntegerField(null=True, blank=True, verbose_name=_('Poor price'))
    good = models.IntegerField(null=True, blank=True, verbose_name=_('Good price'))
    very_good = models.IntegerField(null=True, blank=True, verbose_name=_('Very good price'))
    excellent = models.IntegerField(null=True, blank=True, verbose_name=_('Excellent price'))
    near_mint = models.IntegerField(null=True, blank=True, verbose_name=_('Near mint price'))
    mint = models.IntegerField(null=True, blank=True, verbose_name=_('Mint price'))
    cassette = models.OneToOneField('Cassette', on_delete=models.CASCADE,
                                    related_name='prices',
                                    verbose_name=_('cassette'))

    class Meta:
        verbose_name = _('Price')
        verbose_name_plural = _('Prices')

    def __str__(self):
        return f'{self.cassette} prices'


class Cassette(models.Model):
    """Модель кассеты"""
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, verbose_name=_('uuid'))
    # user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name=_('User'))
    coil = models.BooleanField(verbose_name=_('Coil'), null=True, blank=True)
    slim_case = models.BooleanField(verbose_name=_('Slim case'), null=True, blank=True)
    comment = models.TextField(verbose_name=_('Comments'), null=True, blank=True,)
    category = models.ForeignKey(Category, default=1, related_name='cassettes', on_delete=models.PROTECT, verbose_name=_('Category'))
    brand = models.ForeignKey(CassetteBrand, on_delete=models.PROTECT, related_name='cassettes', verbose_name=_('Brand'))
    tape_type = models.ForeignKey(CassetteType, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('tape type'))
    model = models.ForeignKey(CassetteModel, null=True, blank=True,on_delete=models.PROTECT, verbose_name=_('Model'))
    technology = models.ForeignKey(CassetteTechnology, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('technology'))
    manufacturer = models.ForeignKey(CassetteManufacturer, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('manufacturer'))
    series = models.ForeignKey(CassetteSeries, null=True, blank=True, on_delete=models.CASCADE, verbose_name=_('series'))
    sort = models.ForeignKey(CassetteSort, null=True, blank=True, on_delete=models.CASCADE, verbose_name=_('sort'))
    # collection = models.ForeignKey(CassetteCollection, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('Collection'))
    tape_length = models.ForeignKey(CassetteTapeLength, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('tape Length'))
    year_release = models.IntegerField(null=True, blank=True, verbose_name=_('year Release'))
    country = models.ForeignKey(Country, related_name='country_cassettes', blank=True, null=True, on_delete=models.PROTECT, verbose_name=_('country'))
    markets = models.ManyToManyField(Country,
                                     blank=True,
                                     related_name='markets_cassettes',
                                     verbose_name=_('markets'))
    created = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name=_('date of comment created'))
    updated = models.DateTimeField(auto_now=True, auto_now_add=False, verbose_name=_('date of comment updated'))
    upload_row = models.IntegerField(null=True, blank=True) # temp field to match data at upload process

    class Meta:
        default_related_name = 'cassettes'
        verbose_name = _('cassette')
        verbose_name_plural = _('cassettes')


    def get_absolute_url(self):
        return reverse('catalog:cassette', kwargs={'id': self.pk})

    def __str__(self):
        if self.brand:
            brand = f' {self.brand.title}'
        else:
            brand = ''
        if self.model:
            model = f' {self.model.title}'
        else:
            model = ''

core/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Country(models.Model):
    title = models.CharField(max_length=200, verbose_name=_('country'))

    class Meta:
        verbose_name = _('country')
        verbose_name_plural = _('countries')
        ordering = ('title', )

    def __str__(self):
        return self.title


class Language(models.Model):
    title = models.CharField(max_length=200, verbose_name=_('language'))

    class Meta:
        verbose_name = _('language')
        verbose_name_plural = _('languages')
        ordering = ('title',)

    def __str__(self):
        return self.title


class GlobalText(models.Model):
    system_name = models.CharField(max_length=200, verbose_name=_(
        'system name'))
    admin_name = models.CharField(max_length=200, verbose_name=_(
        'admin name'))
    title = models.CharField(blank=True, max_length=200, verbose_name=_(
        'title'))
    text = models.TextField(blank=True, verbose_name='text')

    class Meta:
        verbose_name = _('global text')
        verbose_name_plural = _('global texts')
        ordering = ('system_name',)

    def __str__(self):
        return self.admin_name

core/views.py
from django.db.models import F, Count
from django.shortcuts import render

from .models import GlobalText
from catalog.models import Category, Cassette, CassetteComment
from users.models import User



def homepage(request):
    queryset = Category.objects.annotate(
        cassette_count=Count('cassettes'),
    ).filter(
        is_published=True,
        is_published_to_home=True
    )
    main_info_text_1, _ = GlobalText.objects.get_or_create(
        system_name='main_info_text_1')
    main_info_text_2, _ = GlobalText.objects.get_or_create(
        system_name='main_info_text_2')

    context = {
        'collector_list': User.objects.order_by(F('rating').desc(nulls_last=True))[:5],
        'cassette_list': Cassette.objects.select_related(
            'category', 'brand', 'tape_type', 'model', 'technology',
            'manufacturer', 'series', 'sort', 'tape_length', 'country'
        ).prefetch_related(
            'images'
        ).order_by(
            '-updated',
        ).all()[:7],
        'category_audio': queryset.filter(type=Category.AUDIO),
        'category_video': queryset.filter(type=Category.VIDEO),
        'comment_list': CassetteComment.objects.filter(is_published=True)[:10],
        'main_info_text_1': main_info_text_1,
        'main_info_text_2': main_info_text_2,
    }
    return render(request, 'core/index.html', context)

templates/core/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load user_filters %}
{% block content %}

    <section class="catalog" id="catalog">
        <div class="container">
            <div class="catalog__wrapper">
                <div class="catalog-info">
                    <div class="catalog-info__item">
                        <h3 class="catalog-info__title">{{ main_info_text_1.title }}</h3>
                        <p class="catalog-info__text">{{ main_info_text_1.text|linebreaksbr }}</p>


                    </div>
                    <div class="catalog-info__item">
                        <h3 class="catalog-info__title">{{ main_info_text_2.title }}</h3>
                        <p class="catalog-info__text">{{ main_info_text_2.text|linebreaksbr }}</p>
                    </div>
                </div>
                <div class="catalog-users">
                    <div class="catalog-users__item">
                    {% comment %}Translators: index / Коллекционеры{% endcomment %}
                        <h4 class="catalog-isers__title">{% translate "Collectors" %}</h4>
                        <ul class="catalog-users__list">
                            {% for collector in collector_list %}
                                <li class="catalog-users__item">
                                    <a href="{% url 'users:collector' id=collector.id %}">{{ collector.first_name }} {{ collector.last_name }}<span>[{{ collector.username }}]</span></a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    <div class="catalog-users__item">
                        {% comment %}Translators: index / Редакторы{% endcomment %}
                        <h4 class="catalog-isers__title">{% translate "Editors" %}</h4>
                            <ul class="catalog-users__list">
                            </ul>
                    </div>
                    <div class="catalog-users__item">
                        {% comment %}Translators: index / Обменники{% endcomment %}
                        <h4 class="catalog-isers__title">{% translate "Exchangers" %}</h4>
                            <ul class="catalog-users__list">
                            </ul>
                    </div>
                </div>
            </div>

            <div class="categories">
                <ul class="categories__list">
                    {% for category in category_audio %}
                        <li class="categories__item">
                            <a href="{% url 'catalog:catalog-detail' slug=category.slug %}" class="categories__link">
                                {% if category.image %}
                                    <img src="{{ category.image.url }}" alt="{{ category.title }}" class="categories__img">
                                {% endif %}
                                <div class="categories__wrapper">
                                    <h1 class="categories__title">{{ category }}</h1>
                                    {% comment %}Translators: index / Объявлений{% endcomment %}
                                    <p class="categories__ads-count">{{ category.cassette_count }} {% translate "offers" %}</p>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
                <span class="categories__line"></span>
                <ul class="categories__list">
                    {% for category in category_video %}
                        <li class="categories__item">
                            <a href="{% url 'catalog:catalog-detail' slug=category.slug %}" class="categories__link">
                                {% if category.image %}
                                    <img src="{{ category.image.url }}" alt="{{ category.title }}" class="categories__img">
                                {% endif %}
                                <div class="categories__wrapper">
                                    <h1 class="categories__title">{{ category }}</h1>
                                    {% comment %}Translators: index / Объявлений{% endcomment %}
                                    <p class="categories__ads-count">{{ category.cassette_count}} {% translate "offers" %}</p>
                                </div>
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </section>

    <section class="last-update" id="last-update">
        <div class="container">
        {% comment %}Translators: index / Последние обновления{% endcomment %}
            <h2 class="section__title last-update__title">{% translate "Latest updates" %}</h2>
            <ul class="products">
                {% for cassette in cassette_list %}
                    <li class="product">
                        <a href="{% url 'catalog:cassette' id=cassette.id %}" class="product__link">
                            {% if cassette.images.exists %}
                                {% with cover=cassette.images|image_cover %}
                                    {% if cover.image %}
                                        <img src="{{ cover.image.url }}" alt="{{ cassette }}" class="product__img">
                                    {% endif %}
                                {% endwith %}
                            {% endif %}
                            <p class="product__categories">{{ cassette.category }}</p>
                            <p class="product__name">
                                {{ cassette.brand.title }}
                                {% if cassette.model %} {{ cassette.model.title }}{% endif %}
                                {% if cassette.series %} {{ cassette.series.title }}{% endif %}
                                {% if cassette.tape_type %} {{ cassette.tape_type.title }}{% endif %}
                                {% if cassette.tape_length %} {{ cassette.tape_length.tape_length }}{% endif %}
                                {% if cassette.country %} {{ cassette.country.title }}{% endif %}
                                {% if cassette.year_release %} ({{ cassette.year_release }}){% endif %} </p>
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </section>

    <section class="comment-last">
        <div class="container">
        {% comment %}Translators: index / Последние комментарии{% endcomment %}
            <h2 class="section__title comment-last__title">{% translate "Latest comments" %}</h2>
            <ul class="comment-last__list">
                {% for comment in comment_list %}
                    <li class="comment-last__item">
                        {% if comment.cassette.cassettesimage_set.first.package_front_side %}
                            <img src="{{ comment.cassette.cassettesimage_set.first.package_front_side.url }}" alt="" class="comment-last__img">
                        {% endif %}
                        <div class="comment-last__wrapper">
                            <a href="{% url 'catalog:cassette' id=comment.cassette.id %}" class="comment-last__product">
                                {{ comment.cassette.brand }} - {{ comment.cassette.series }}, {{ comment.cassette.brand.country }} ({{ comment.cassette.year_release }})
                            </a>
                            <p class="comment-last__text">{{ comment.comment|truncatechars:255 }}
                                {% comment %}Translators: index / подробнее{% endcomment %}
                                <a href="{% url 'catalog:cassette' id=comment.cassette.id %}#comment_{{ comment.id }}" class="comment-last__more more"> {% translate "more" %}</a></p>
                        </div>
                        <div class="comment-last__author">
                        {% comment %}Translators: index / Комментарий от{% endcomment %}
                            <p class="comment-last__from">{% translate "Comment from" %}</p>
                            <div class="user ">
                                <img src="{% if comment.user.image %}{{ comment.user.image.url }}{% else %}{% static 'img/avatar.jpg' %}{% endif %}" alt="" class="user__avatar">
                                <div class="user__wrapper">
                                    <h2 class="user__name">{{ comment.user.first_name }} {{ comment.user.last_name }}</h2>
                                    <p class="user__nick">[{{ comment.user.username }}]</p>
                                </div>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}