catalog/urls.py
from django.urls import path
from .views import CategoryDetailView, CategoryListView, CassetteBrandListView, CassetteBrandDetail, \
    CassetteCatalogBrandDetailView, TechnologyListView, CassetteDetailView, CassetteCreateView, CassetteUpdateView

app_name = 'catalog'

urlpatterns = [
    path('', CategoryListView.as_view(), name='catalog-list'),
    path('category/<slug>/<brand_slug>/', CassetteCatalogBrandDetailView.as_view(), name='catalog-brand-cassette-list'),
    path('category/<slug>/', CategoryDetailView.as_view(), name='catalog-detail'),
    path('brands/', CassetteBrandListView.as_view(), name='brand-list'),
    path('brands/<slug>/', CassetteBrandDetail.as_view(), name='brand-detail'),
    path('technology/', TechnologyListView.as_view(), name='technologies'),
    path('cassettes/<int:id>/', CassetteDetailView.as_view(), name='cassette'),
    path('cassettes/add/', CassetteCreateView.as_view(), name='cassette_create'),
    path('cassettes/<int:id>/update/', CassetteUpdateView.as_view(), name='cassette_update'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import homepage

app_name = 'core'

urlpatterns = [
    path('', homepage, name='home-page'),
]

kassets/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _

from kassets import settings
from users.views import GoogleSignInView

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('auth/', include('users.urls')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
    path('catalog/', include('catalog.urls')), path('', include('core.urls')),
    path('lists/', include('collection_management.urls'))
)

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


admin.site.index_title = _('Site Content Management')
admin.site.site_header = _('Tape Collector Administration')
admin.site.site_title = _('Tape Collector administration')

users/urls.py
# Импортируем из приложения django.contrib.auth нужный view-класс
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetView, PasswordChangeView, \
    PasswordChangeDoneView
from django.urls import path
from . import views
from .views import Profile, ProfileUpdate

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_change/', PasswordChangeView.as_view(template_name='users/edit-password.html'),
         name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/edit-password-done.html'),
         name='password_change_done'),
    path('profile/', Profile.as_view(), name='profile'),
    path('profile-update/', ProfileUpdate.as_view(), name='profile-update'),
    path('collectors/', views.Collectors.as_view(), name='collectors'),
    path('collector/<int:id>/', views.Collector.as_view(), name='collector'),
]

catalog/models.py
import random
import string
import uuid
from django.db import models
from django.db.models import F, Min, Max
from django.urls import reverse
from django.utils.html import mark_safe
from django.utils.translation import gettext_lazy as _

from pytils.translit import slugify

from core.models import Country
from users.models import Country, User


def title_slugify(model, title):
    slug = slugify(title)
    if model.objects.filter(slug=slug).exists():
        letters = string.ascii_lowercase
        slug = slug + '-' + ''.join(random.choice(letters) for _ in range(3))
    return slug[:50]


class PublishModelManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=True)


class BaseModel(models.Model):
    """Базовая модель"""
    title = models.CharField(max_length=255, unique=True, verbose_name=_('title'))
    slug = models.SlugField(unique=True, blank=True, verbose_name=_('Url/Slug'))
    is_published = models.BooleanField(default=True, verbose_name=_('Publish'))
    created = models.DateTimeField(auto_now=False, auto_now_add=True,
                                   verbose_name=_('Date of created'))
    updated = models.DateTimeField(auto_now=True, auto_now_add=False,
                                   verbose_name=_('Date of updated'))

    objects = models.Manager()
    published_objects = PublishModelManager()

    class Meta:
        abstract = True
        ordering = ('title', )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # self.slug = slugify(self.title)
        self.slug = title_slugify(self.__class__, self.title)
        super().save(*args, **kwargs)


class Category(BaseModel):
    """Модель категории"""
    AUDIO = 'audio'
    VIDEO = 'video'
    CATEGORY_TYPE = ((AUDIO, _('Audio')), (VIDEO, _('Video')),)
    type = models.CharField(max_length=5, choices=CATEGORY_TYPE, default=AUDIO)
    image = models.ImageField(upload_to='category', blank=True)
    logo = models.ImageField(upload_to='category_logo', blank=True)
    description = models.TextField(blank=True)
    brands = models.ManyToManyField('CassetteBrand', related_name='categories', blank=True, verbose_name=_('Brands'))
    is_published_to_home = models.BooleanField(default=False, verbose_name=_('Publish to home page'))
    display_order = models.IntegerField(blank=True, null=True, verbose_name=_('display order'))

    def cassettes_count(self):
        """Считаем количество кассет в категории"""
        return Cassette.objects.filter(brand__categories__slug=self.slug).count()

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ('display_order', 'type', 'title')



class CassetteBrand(BaseModel):
    """Модель бренда"""
    country = models.ForeignKey(Country, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('country'))
    description = models.TextField(blank=True, verbose_name=_('description'))
    image = models.ImageField(upload_to='brands', blank=True, verbose_name=_('image'))

    def cassette_year(self):
        """Вычисляем минимальный и максимальный год кассет в данном бренде"""
        year_period = Cassette.objects.filter(brand=self).aggregate(min=Min('year_release'), max=Max('year_release'))
        return year_period

    def admin_preview(self):
        return mark_safe(
            f'<img src = "{self.image.url}" width = "200"/>')
    admin_preview.short_description = _('image preview')

    def admin_list_preview(self):
        if self.image:
            return mark_safe(
                f'<img src = "{self.image.url}" width = "50"/>')

    admin_list_preview.short_description = _('image')

    class Meta:
        verbose_name = _('brand')
        verbose_name_plural = _('brands')
        ordering = ('title',)




class CassetteModel(BaseModel):
    """Модель модели кассеты"""
    title = models.CharField(max_length=255, unique=False, verbose_name=_('title'))
    brand = models.ForeignKey(CassetteBrand, on_delete=models.PROTECT, verbose_name=_('brand'))
    description = models.TextField(blank=True, verbose_name=_('description'))

    class Meta:
        verbose_name = _('Model')
        verbose_name_plural = _('Models')
        ordering = ('title',)

    def __str__(self):
        return f'{self.title} ({self.brand})'


class CassetteType(BaseModel):
    """Модель типа кассеты"""
    class Meta:
        verbose_name = _('Type')
        verbose_name_plural = _('Types')
        ordering = ('title',)



class CassetteTechnology(BaseModel):
    """Модель технологии кассеты"""
    class Meta:
        verbose_name = _('Technology')
        verbose_name_plural = _('Technologies')
        ordering = ('title',)


class CassetteManufacturer(BaseModel):
    """Модель производителя кассеты"""
    class Meta:
        verbose_name = _('Manufacturer')
        verbose_name_plural = _('Manufacturers')
        ordering = ('title',)


class CassetteSeries(BaseModel):
    """Модель серии кассеты"""
    class Meta:
        verbose_name = _('Series')
        verbose_name_plural = _('Series')
        ordering = ('title',)


class CassetteSort(BaseModel):
    """Модель серии кассеты"""
    class Meta:
        verbose_name = _('sort')
        verbose_name_plural = _('sorts')
        ordering = ('title',)


class CassetteCollection(BaseModel):
    """Модель коллекции"""
    class Meta:
        verbose_name = _('Collection')
        verbose_name_plural = _('Collections')
        ordering = ('title',)


class CassetteTapeLength(models.Model):
    """Модель длины ленты"""
    tape_length = models.CharField(max_length=32,
                                   verbose_name=_('tape length'))

    class Meta:
        verbose_name = _('tape length')
        verbose_name_plural = _('tape lengtes')
        ordering = ('tape_length',)

    def __str__(self):
        return self.tape_length


class CassettePrice(models.Model):
    """Различные варианты цены в зависимости от состояния"""
    poor = models.IntegerField(null=True, blank=True, verbose_name=_('Poor price'))
    good = models.IntegerField(null=True, blank=True, verbose_name=_('Good price'))
    very_good = models.IntegerField(null=True, blank=True, verbose_name=_('Very good price'))
    excellent = models.IntegerField(null=True, blank=True, verbose_name=_('Excellent price'))
    near_mint = models.IntegerField(null=True, blank=True, verbose_name=_('Near mint price'))
    mint = models.IntegerField(null=True, blank=True, verbose_name=_('Mint price'))
    cassette = models.OneToOneField('Cassette', on_delete=models.CASCADE,
                                    related_name='prices',
                                    verbose_name=_('cassette'))

    class Meta:
        verbose_name = _('Price')
        verbose_name_plural = _('Prices')

    def __str__(self):
        return f'{self.cassette} prices'


class Cassette(models.Model):
    """Модель кассеты"""
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, verbose_name=_('uuid'))
    # user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name=_('User'))
    coil = models.BooleanField(verbose_name=_('Coil'), null=True, blank=True)
    slim_case = models.BooleanField(verbose_name=_('Slim case'), null=True, blank=True)
    comment = models.TextField(verbose_name=_('Comments'), null=True, blank=True,)
    category = models.ForeignKey(Category, default=1, related_name='cassettes', on_delete=models.PROTECT, verbose_name=_('Category'))
    brand = models.ForeignKey(CassetteBrand, on_delete=models.PROTECT, related_name='cassettes', verbose_name=_('Brand'))
    tape_type = models.ForeignKey(CassetteType, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('tape type'))
    model = models.ForeignKey(CassetteModel, null=True, blank=True,on_delete=models.PROTECT, verbose_name=_('Model'))
    technology = models.ForeignKey(CassetteTechnology, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('technology'))
    manufacturer = models.ForeignKey(CassetteManufacturer, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('manufacturer'))
    series = models.ForeignKey(CassetteSeries, null=True, blank=True, on_delete=models.CASCADE, verbose_name=_('series'))
    sort = models.ForeignKey(CassetteSort, null=True, blank=True, on_delete=models.CASCADE, verbose_name=_('sort'))
    # collection = models.ForeignKey(CassetteCollection, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('Collection'))
    tape_length = models.ForeignKey(CassetteTapeLength, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('tape Length'))
    year_release = models.IntegerField(null=True, blank=True, verbose_name=_('year Release'))
    country = models.ForeignKey(Country, related_name='country_cassettes', blank=True, null=True, on_delete=models.PROTECT, verbose_name=_('country'))
    markets = models.ManyToManyField(Country,
                                     blank=True,
                                     related_name='markets_cassettes',
                                     verbose_name=_('markets'))
    created = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name=_('date of comment created'))
    updated = models.DateTimeField(auto_now=True, auto_now_add=False, verbose_name=_('date of comment updated'))
    upload_row = models.IntegerField(null=True, blank=True) # temp field to match data at upload process

    class Meta:
        default_related_name = 'cassettes'
        verbose_name = _('cassette')
        verbose_name_plural = _('cassettes')


    def get_absolute_url(self):
        return reverse('catalog:cassette', kwargs={'id': self.pk})

    def __str__(self):
        if self.brand:
            brand = f' {self.brand.title}'
        else:
            brand = ''
        if self.model:
            model = f' {self.model.title}'
        else:
            model = ''

templates/includes/footer.html
{% load static %}
{% load i18n %}
<footer class="footer" id="footer">
    <div class="container">
        <div class="footer-top">
            <a href="#" class="logo logo_footer">
                <img src="{% static 'img/logo.jpg' %}" alt="TapeCollector">
            </a>
            <ul class="footer-top__menu">
                <li class="footer-top__menu-item">
                    {% comment %}Translators: Footer / О сайте{% endcomment %}
                    <a href="#">{% translate "About" %}</a>
                </li>
                <li class="footer-top__menu-item">
                    {% comment %}Translators: Footer / Поддержка {% endcomment %}
                    <a href="#">{% translate "Support" %}</a>
                </li>
                <li class="footer-top__menu-item">
                    {% comment %}Translators: Footer / Условия обслуживания{% endcomment %}
                    <a href="#">{% translate "Terms & Conditions" %}</a>
                </li>
            </ul>
        </div>
        <div class="footer-bottom">
            <p class="footer-bottom__credits">Founded in 2023. © All trademarks ™ and brand names ® belong to their respective owners.</p>
            {% comment %}Translators: Footer / Политика Конфиденциальности<{% endcomment %}
            <a href="#" class="footer-bottom__politics">{% translate "Privacy Statement" %}</a>
        </div>
    </div>
</footer>

templates/includes/header.html
{% load static %}
{% load i18n %}

<header class="header" id="header">
    <div class="header__wrapper">
        <div class="container">
            <div class="header-top">
                <a href="/" class="logo">
                    <img src="{% static 'img/logo.jpg' %}" alt="TapeCollector">
                </a>
                <div class="header-top__search">
                    {% comment %}Translators: Search lable in header{% endcomment %}
                    <input type="text" placeholder="{% translate "Search" %}">
                </div>
                <div class="header-top__wrapper">

                    {#                                        <div class="header-top__change-lang dropdown">#}
                    {#                                            <button class="header-top__lang dropdown__select">English</button>#}
                    {#                                            <ul class="dropdown__options header-top__options">#}
                    {#                                                <li data-value="По бренду" class="active">English</li>#}
                    {#                                                <li data-value="По бренду">Russian</li>#}
                    {#                                            </ul>#}
                    {#                                        </div>#}
                    {##}
                    {#                                        <form action="{% url 'set_language' %}" method="post">#}
                    {#                                            {% csrf_token %}#}
                    {#                                            <input name="next" type="hidden" value="{{ redirect_to }}">#}
                    {#                                            <select name="language">#}
                    {#                                                {% get_current_language as LANGUAGE_CODE %}#}
                    {#                                                {% get_available_languages as LANGUAGES %}#}
                    {#                                                {% get_language_info_list for LANGUAGES as languages %}#}
                    {#                                                {% for language in languages %}#}
                    {#                                                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>#}
                    {#                                                        {{ language.name_local }} ({{ language.code }})#}
                    {#                                                    </option>#}
                    {#                                                {% endfor %}#}
                    {#                                            </select>#}
                    {#                                            <input type="submit" value="Go">#}
                    {#                                        </form>#}
{#                    <img src="{% static 'img/lang-icon.svg' %}">#}
                    <!-- <form action="{% url 'set_language' %}" method="post">
                        {% csrf_token %}
                        <input name="next" type="hidden" value="{{ redirect_to }}">
                        <div class="header-top__change-lang dropdown">
                            <select name="language" class="header-top__lang dropdown__select" onchange="this.form.submit()">
                                {% get_current_language as LANGUAGE_CODE %}
                                {% get_available_languages as LANGUAGES %}
                                {% get_language_info_list for LANGUAGES as languages %}
                                {% for language in languages %}
                                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected
                    {% endif %}>
                                        {{ language.name_local }}
                                    </option>
                                {% endfor %}
                            </select>
                        </div>
                    </form>

-->
                    <div class="header-top__profile">
                        {% if request.user.is_authenticated %}
                            <a href="{% url 'users:profile' %}">
                                {% if request.user.first_name or request.user.last_name %}
                                    {{ request.user.first_name }} {{ request.user.last_name }}
                                {% else %}
                                    {{ request.user.username }}
                                {% endif %}
                            </a> |
                            {% comment %}Translators: header / Logout{% endcomment %}
                            <a href="{% url 'users:logout' %}">{% translate "Logout" %}</a>
                        {% else %}
                            <button type="button" class="btn btn_ghost header-top__btn-login btn-modal"
                                    {% comment %}Translators: header / Вход от{% endcomment %}
                                    data-modal="loginModal">{% translate "Log in" %}
                            </button>
                            {% comment %}Translators: header / Регистрация{% endcomment %}
                            <a class="btn btn_fill header-top__btn-registration btn-modal"
                               href="{% url 'users:signup' %}">{% translate "Signup" %}</a>

                        {% endif %}
                    </div>
                </div>
                <button class="burger">
                    <span></span>
                </button>
            </div>

            <div class="header-brands">
                <ul class="header-brands__audio-cassette">
                    {% for category in category_list %}
                        {% if category.logo %}
                            <li class="header-brands__item">
                                <a href="{% url 'catalog:catalog-detail' slug=category.slug %}"
                                   class="header-brands__link">
                                    <img src="{{ category.logo.url }}" alt="{{ category }}">
                                </a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
    <nav class="header-menu">
        <div class="container">
            <div class="header-menu__wrapper">
                <ul class="header-menu__list">
                    <li class="header-menu__item">
                        <a href="{% url 'catalog:catalog-list' %}">{% translate "Catalog" %}</a>
                    </li>
                    <li class="header-menu__item">
                        <a href="{% url 'catalog:brand-list' %}">{% translate "Brands" %}</a>
                    </li>
                    <li class="header-menu__item">
                        <a href="{% url 'catalog:technologies' %}">{% translate "Technologies" %}</a>
                    </li>
                    <li class="header-menu__item">
                        <a href="{% url 'users:collectors' %}">{% translate "Collectors" %}</a>
                    </li>
                    <li class="header-menu__item">
                        <a href="{% url 'users:profile' %}">{% translate "My lists" %}</a>
                    </li>
                    {% if user.is_authenticated %}
                        {% if user.is_moderator or user.is_superuser %}
                            <li class="header-menu__item">
                                <a href="{% url 'catalog:cassette_create' %}">{% translate "Add cassette" %}</a>
                            </li>
                        {% endif %}
                    {% endif %}
                </ul>
                <ul class="header-menu__list">
                    <li class="header-menu__item header-menu__item_left">
                        <a href="help.html">{% translate "Help" %}</a>
                    </li>
                    <li class="header-menu__item header-menu__item_left">
                        <a href="#">{% translate "Merchandise" %}</a>
                    </li>
                    <li class="header-menu__item header-menu__item_left">
                        <a href="support.html">{% translate "Support" %}</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

templates/includes/js.html
{% load static %}
<script src="{% static 'js/add-photo.js' %}"></script>
<script src="{% static 'js/drop-and-drag.js' %}"></script>
<script src="{% static 'js/modal.js' %} "></script>
<script src="{% static 'js/burger.js' %}"></script>
<script src="{% static 'js/dropdown.js' %}"></script>

templates/includes/modals.html
{% load static socialaccount %}
{% load socialaccount %}
{% load i18n %}
<!-- Modal -->
<div class="modal" id="loginModal">
    <div class="modal__wrapper">
        <img src="{% static 'img/close-icon.svg' %}" alt="" class="modal__close">
        {% comment %}Translators: Modal / Войти или создать профиль {% endcomment %}
        <h1 class="modal__title">{% translate "Log in or create account" %}</h1>
        {% comment %}Translators: Modal / Войти с помощью Google{% endcomment %}
{#        <a href="/accounts/google/login/" class="authorization-google">{% translate "Log in with Google" %}</a>#}
        <a href="{% provider_login_url 'google' %}?next={{ request.get_full_path }}" class="authorization-google">{% translate "Log in with Google" %}</a>
        {% comment %}Translators: Modal / или{% endcomment %}
        <p class="modal__replace">{% translate "or" %}</p>
        <form action="{% url 'users:login' %}" class="modal__form" method="post">
            {% csrf_token %}
            {% comment %}Translators: Modal / Email{% endcomment %}
            <input type="text" name="username" class="input-cust modal__input" placeholder="{% translate "Email" %}">
            {% comment %}Translators: Modal / Пароль {% endcomment %}
            <input type="password" name="password" class="input-cust modal__input" placeholder="{% translate "Password" %}">
            {% comment %}Translators: Modal / Забыли пароль?{% endcomment %}
            <p class="modal__not-pass">{% translate "Forgot password?" %}</p>
            {% comment %}Translators: Modal / Войти{% endcomment %}
            <button type="submit" class="btn modal__btn btn_fill">{% translate "Log in" %}</button>
        </form>
        <div class="modal__wrapper-block">
            {% comment %}Translators: Modal / Еще нет аккаунта?{% endcomment %}
            <p class="modal__text">{% translate "Don't have an account?" %}</p>
            {% comment %}Translators: Modal / Зарегистрируйтесь.{% endcomment %}
            <a href="#" class="modal__login header-top__btn-registration btn-modal" data-modal="regModal">{% translate "Sign up" %}</a>
        </div>
    </div>
</div>
<!--  -->
<div class="modal" id="regModal">
    <div class="modal__wrapper">
        <img src="{% static 'img/close-icon.svg' %}" alt="" class="modal__close">
        {% comment %}Translators: Modal / Регистрация{% endcomment %}
        <h1 class="modal__title">{% translate "Create Account" %}</h1>
        {% comment %}Translators: Modal / Пожалуйста, введите вашу электронную почту ниже и мы отправим на нее
            ссылку для создания нового аккаунта. {% endcomment %}
        <p class="modal__text modal__text_indent ">{% translate "Please enter your email below and we will send a link to create a new account." %}</p>
        {% comment %}Translators: Modal / Войти с помощью Google{% endcomment %}
        <a href="{% provider_login_url 'google' %}" class="authorization-google">{% translate "Log in with Google" %}</a>
        {% comment %}Translators: Modal / или{% endcomment %}
        <p class="modal__replace">{% translate "or" %}</p>
        <form class="modal__form" method="post" action="{% url 'account_signup' %}">
            {% csrf_token %}
            {% comment %}Translators: Modal / Email{% endcomment %}
            <input type="text" name="email" class="input-cust modal__input" placeholder="{% translate "Email" %}">
            {% comment %}Translators: Modal / Username{% endcomment %}
            <input type="text" name="username" class="input-cust modal__input" placeholder="{% translate "Username" %}">
            {% comment %}Translators: Modal / Password{% endcomment %}
            <input type="password" name="password1" class="input-cust modal__input" placeholder="{% translate "Password" %}">
            {% comment %}Translators: Modal / Password repeat{% endcomment %}
            <input type="password" name="password2" class="input-cust modal__input" placeholder="{% translate "Password repeat" %}">
            {% comment %}Translators: Modal / Подтвердить{% endcomment %}
            <button type="submit" class="btn modal__btn btn_fill">{% translate "Confirm" %}</button>
        </form>
        <div class="modal__wrapper-block">
            {% comment %}Translators: Modal / Уже есть аккаунт?{% endcomment %}
            <p class="modal__text">{% translate "Already have an account?" %}</p>
            {% comment %}Translators: Modal / Войдите{% endcomment %}
            <a href="#" class="modal__login header-top__btn-registration btn-modal" data-modal="loginModal">{% translate "Log in" %}</a>
        </div>
    </div>
</div>