collection_management/urls.py
from django.urls import path
from .views import CollectionListView, ExchangeListView, SaleListView, WishlistListView

app_name = 'lists'

urlpatterns = [
    path('collection/<int:collector_id>/', CollectionListView.as_view(), name='collection'),
    path('wishlist/<int:collector_id>/', WishlistListView.as_view(), name='wishlist'),
    path('exchange/<int:collector_id>/', ExchangeListView.as_view(), name='exchange'),
    path('sale/<int:collector_id>/', SaleListView.as_view(), name='sale'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import homepage

app_name = 'core'

urlpatterns = [
    path('', homepage, name='home-page'),
]

kassets/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _

from kassets import settings
from users.views import GoogleSignInView

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('auth/', include('users.urls')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
    path('catalog/', include('catalog.urls')), path('', include('core.urls')),
    path('lists/', include('collection_management.urls'))
)

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


admin.site.index_title = _('Site Content Management')
admin.site.site_header = _('Tape Collector Administration')
admin.site.site_title = _('Tape Collector administration')

users/urls.py
# Импортируем из приложения django.contrib.auth нужный view-класс
from django.contrib.auth.views import LogoutView, LoginView, PasswordResetView, PasswordChangeView, \
    PasswordChangeDoneView
from django.urls import path
from . import views
from .views import Profile, ProfileUpdate

app_name = 'users'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_change/', PasswordChangeView.as_view(template_name='users/edit-password.html'),
         name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/edit-password-done.html'),
         name='password_change_done'),
    path('profile/', Profile.as_view(), name='profile'),
    path('profile-update/', ProfileUpdate.as_view(), name='profile-update'),
    path('collectors/', views.Collectors.as_view(), name='collectors'),
    path('collector/<int:id>/', views.Collector.as_view(), name='collector'),
]

users/models.py
from datetime import date

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager as DjangoUserManager
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models import F, Q
from django.utils.translation import gettext_lazy as _

# from catalog.models import Cassette, Condition
from core.models import Country, Language


# class Country(models.Model):
#     title = models.CharField(max_length=200, verbose_name=_('country'))
#
#     class Meta:
#         verbose_name = _('country')
#         verbose_name_plural = _('countries')
#
#     def __str__(self):
#         return self.title


class UserManager(DjangoUserManager):
    def get_queryset(self):
        return super().get_queryset().annotate(rating=models.Avg('feedback_collectors__rating_score'))


class User(AbstractUser):
    USER = 'user'
    MODERATOR = 'moderator'
    ADMIN = 'admin'
    USER_ROLES = (
        (USER, _('User')),
        (MODERATOR, _('Moderator')),
        (ADMIN, _('Admin')),
    )
    # USER_LANGUAGE = (
    #     ('English', 'Английский'),
    #     ('Russian', 'Русский'),
    #     ('Spanish', 'Испанский'),
    # )
    role = models.CharField(
        # Можно лучше: Тут обычно задают 9, как в moderator.
        # Я бы закладывался сразу с запасом
        max_length=20,
        choices=USER_ROLES,
        default=USER
    )
    premium = models.BooleanField(default=False)
    image = models.ImageField(blank=True, upload_to='profile')
    bio = models.TextField(blank=True)
    born_date = models.DateField(blank=True, null=True)
    country = models.ForeignKey(Country, related_name='users', blank=True, null=True, on_delete=models.PROTECT)
    language = models.ForeignKey(Language, related_name='users', blank=True, null=True, on_delete=models.PROTECT)
    # language = models.CharField(max_length=200, choices=USER_LANGUAGE)
    website = models.URLField(blank=True)

    objects = UserManager()

    class Meta:
        ordering = ('username',)
        verbose_name = _('user')
        verbose_name_plural = _('users')

    # Можно лучше: можно добавить тут property для удобства
    @property
    def is_admin(self):
        # Надо исправить: Везде, где мы используем роли - не используем строки,
        # а используем константу
        return (
            self.role == User.ADMIN
            or self.is_superuser
            # Я тут не уверен, считается ли стафф "администратором Django"
            # по спеке, но будем считать, что да
            or self.is_staff
        )

    @property
    def is_moderator(self):
        return self.role == User.MODERATOR


class PublishModelManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=True)


class CollectorFeedback(models.Model):
    """Отзывы о коллекционерах с оценкой для пользовательского рейтинга."""
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name=_('user'),
        related_name="feedback_users",
    )
    collector = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name=_('collector'),
        related_name="feedback_collectors",
    )
    rating_score = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        verbose_name=_('rating score'),
    )
    feedback = models.TextField(verbose_name=_('feedback'))
    is_published = models.BooleanField(default=True,
                                       verbose_name=_('publish'))
    created = models.DateTimeField(auto_now=False, auto_now_add=True,
                                   verbose_name=_('Date of created'))
    updated = models.DateTimeField(auto_now=True, auto_now_add=False,
                                   verbose_name=_('Date of updated'))

    objects = models.Manager()
    published_objects = PublishModelManager()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'collector'],
                name='unique_feedback_relationships',
                violation_error_message=_('Feedback with this User and Collector already exists')
            ),
            models.CheckConstraint(
                check=~Q(user=F('collector')),
                name='prevent_self_feedback',
                violation_error_message=_('Feedback with matching User and Collector is not allowed')
            )
        ]
        ordering = ('-created',)
        verbose_name = _('feedback')
        verbose_name_plural = _('feedbacks')

    def __str__(self):
        return f'{self.collector} -> {self.user}'

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from django import forms

from .models import CollectorFeedback

User = get_user_model()


#  создадим собственный класс для формы регистрации
#  сделаем его наследником предустановленного класса UserCreationForm
class CreationForm(UserCreationForm):
    username = forms.CharField(label='search',
                        widget=forms.TextInput(attrs={'placeholder': _('Username')}))
    email = forms.CharField(label='search',
                               widget=forms.TextInput(attrs={'placeholder': _('Email')}))
    password1 = forms.CharField(label='search',
                               widget=forms.PasswordInput(attrs={'placeholder': _('Password')}))
    password2 = forms.CharField(label='search',
                                 widget=forms.PasswordInput(attrs={'placeholder': _('Password repeat')}))

    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super(CreationForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'input-cust modal__input'


class ProfileForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ('email', 'born_date', 'country', 'image', 'language', 'website', 'bio', 'premium')
        labels = {
            'bio': 'О себе',
        }
        help_texts = {
            'born_date': 'Формат записи (2023-12-31)',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['country'].widget.attrs.update({'class': 'input-cust input-cust_fz14'})
        self.fields['language'].widget.attrs.update({'class': 'input-cust input-cust_fz14'})


class CollectorFeedbackForm(forms.ModelForm):
    rating_score = forms.IntegerField(
        min_value=1,
        max_value=5,
        widget=forms.NumberInput(attrs={
            'class': 'input-cust',
            'placeholder': _('Rate collector'),
        }),
        label=_('Rating score')
    )
    feedback = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'textarea-cust',
                'placeholder': _('Leave feedback'),
                'rows': '2',
            }
        ),
        label=_('Feedback')
    )

    class Meta:
        model = CollectorFeedback
        fields = ('user', 'collector', 'rating_score', 'feedback') #'user', 'collector',

users/views.py
from django.contrib.auth import get_user_model, authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.utils.decorators import method_decorator

# Импортируем CreateView, чтобы создать ему наследника
from django.views.generic import CreateView, DetailView, UpdateView, ListView
from django.views.generic.edit import FormMixin

# Функция reverse_lazy позволяет получить URL по параметрам функции path()
# Берём, тоже пригодится
from django.urls import reverse_lazy, reverse

# Импортируем класс формы, чтобы сослаться на неё во view-классе
from .forms import CreationForm, ProfileForm, CollectorFeedbackForm
from .models import CollectorFeedback

from allauth.account.views import SignupView, LoginView, PasswordResetView


class GoogleSignInView(SignupView):
    template_name = 'users/google-signup.html'


User = get_user_model()


class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('users:profile')
    template_name = 'users/signup.html'


    def form_valid(self, form):
        # save the new user first
        form.save()
        # get the username and password
        username = self.request.POST['username']
        password = self.request.POST['password1']
        # authenticate user then login
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return HttpResponseRedirect(self.success_url)


@method_decorator(login_required, name='dispatch')
class Profile(DetailView):
    model = User
    template_name = 'users/user-profile.html'

    def get_object(self, queryset=None):
        user = self.request.user
        return user

    def get_context_data(self, **kwargs):
        context = super(Profile, self).get_context_data(**kwargs)
        context['feedbacks'] = CollectorFeedback.published_objects.filter(user=self.get_object())
        return context


@method_decorator(login_required, name='dispatch')
class ProfileUpdate(UpdateView):
    model = User
    template_name = 'users/user-settings.html'
    form_class = ProfileForm
    success_url = '/auth/profile/'

    def get_object(self, queryset=None):
        user = self.request.user
        return user


class Collectors(ListView):
    """Список коллекционеров"""
    model = User
    template_name = 'users/collectors.html'
    context_object_name = 'collector_list'


class Collector(FormMixin, DetailView):
    model = User
    template_name = 'users/collector.html'
    context_object_name = 'object'
    form_class = CollectorFeedbackForm

    def get_object(self, queryset=None):
        return User.objects.get(id=self.kwargs['id'])

    def get_context_data(self, **kwargs):
        feedbacks = CollectorFeedback.published_objects.filter(collector=self.get_object())
        context = super(Collector, self).get_context_data(**kwargs)
        context['feedbacks'] = feedbacks
        context['feedback_provided'] = self.request.user.is_anonymous or feedbacks.filter(user=self.request.user).exists() or self.request.user == self.object
        context['feedback_form'] = CollectorFeedbackForm(
            initial={
                'user': self.request.user,
                'collector': self.object,
            }
        )
        return context

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        # form.user = request.user
        # form.collector = self.object
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(Collector, self).form_valid(form)

    def get_success_url(self):
        return reverse('users:collector', kwargs={'id': self.object.id})

templates/users/edit-password-done.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <section class="edit-password" id="edit-password">
        <div class="container">
            <div class="page__content-center">
                <h1 class="page__title page__title_center page__title_form">Пароль успешно изменен</h1>
                <p class="page__text page__text_center">Ваш пароль был изменен.</p>
            </div>
        </div>
    </section>
{% endblock %}

templates/users/google-signup.html
{% extends "base.html" %}
{% load i18n %}

{% block head_title %}{% trans "Sign In" %}{% endblock %}

{% block content %}
<section class="my-list" id="my-list">
    <div class="container">
        <div class="page__content-center">
            {% if process == "connect" %}
            <h1 class="page__title page__title_center">{% blocktrans with provider.name as provider %}Connect {{ provider }}{% endblocktrans %}</h1>
            <p class="page__text page__text_center">{% blocktrans with provider.name as provider %}You are about to
                connect a new third party account from {{ provider }}.{% endblocktrans %}</p>
            {% else %}
            <h1 class="page__title page__title_center">{% blocktrans with provider.name as provider %}Sign In Via {{ provider }}{% endblocktrans %}</h1>

            <p class="page__text page__text_center">{% blocktrans with provider.name as provider %}You are about to sign
                in using a third party account from {{ provider }}.{% endblocktrans %}</p>
            {% endif %}

            <div class="page__btns">
                <form method="post">
                    {% csrf_token %}
                    <button class="btn page__btn btn_ghost" type="submit">{% trans "Continue" %}</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/users/logged_out.html
{# Это код файла templates/users/logged_out.html #}
{% extends 'base.html' %}
{% load i18n %}
{% block title %}You logout!{% endblock %}
{% block content %}
    <section class="my-list" id="my-list">
        <div class="container">
            <div class="page__content-center">
                <p class="page__text page__text_center">{% translate "You logout" %}!</p>
            </div>
        </div>
    </section>
{% endblock %} 

templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% load static %}
{% block content %}
    {% load user_filters %}
    <section class="my-list" id="my-list">
        <div class="container">
            <div class="page__content-center">
                <div class="card-body">

                    <div class="">
                        <img src="{% static '/static/img/close-icon.svg' %}" alt="" class="modal__close">
                        <h1 class="modal__title">Войти или создать профиль</h1>
                        <a href="/accounts/google/login/" class="authorization-google">Войти с помощью Google</a>
                        <p class="modal__replace">или</p>
                        <form action="{% url 'login' %}" class="modal__form" method="post">
                            {% csrf_token %}
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-danger">
                                        {{ error|escape }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <input type="text" name="username" class="input-cust modal__input" placeholder="Email">
                            <input type="password" name="password" class="input-cust modal__input" placeholder="Пароль">
                            <p><a href="{% url 'users:password_reset' %}" class="modal__not-pass">Забыли пароль?</a></p>
                            <button type="submit" class="btn modal__btn btn_fill">Войти</button>
                        </form>
                        <div class="modal__wrapper-block">
                            <p class="modal__text">Еще нет аккаунта?</p>
                            <a href="{% url 'users:signup' %}" class="modal__login header-top__btn-registration btn-modal" >Зарегистрируйтесь.</a>
                        </div>
                    </div>
                </div> <!-- card body -->
            </div>
        </div>
    </section>
{% endblock %}

templates/users/signup.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% translate "Sign up" %}{% endblock %}
{% block content %}
    <section class="my-list" id="my-list">
        <div class="container">
            <div class="page__content-center">
                <div class="card-body">
                    <div>
                        <h1 class="modal__title">{% translate "Signup" %}</h1>
                        <p class="modal__text modal__text_indent ">
                            {% translate "Please enter your email below and we will send a link to create a new account." %}
{#                            Пожалуйста, введите вашу электронную почту ниже и мы отправим на нее ссылку для создания нового аккаунта.#}
                        </p>
                        <form method="post" action="{% url 'users:signup' %}">
                            {% csrf_token %}
                            {% for field in form %}
                                {{ field }}
                                {% if form.errors %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-danger">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                        <div class="alert alert-danger">
                                            {{ error|escape }}
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                            <input type="submit" class="btn header-top__btn-registration btn-modal" value="{% translate "Sign up" %}">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %} 

templates/users/user-profile.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
    <section class="collector-user section_breadcrumb" id="collector-user">
        <div class="container">
            <div class="collector-user__wrapper">
                <div class="collector-user__list">
                    <h4 class="collector-user__list-title collector-user__list-title_medium">{% translate "My lists" %}</h4>
                    <a href="{% url 'users:profile-update' %}" class="collector-user__buy-object">{% translate "Edit profile" %}</a>
                    <a href="#" class="collector-user__print">{% translate "Print collection" %}</a>
                    <ul class="tabs__list">
                        <li class="tabs__item">
                            <a href="{% url 'lists:collection' collector_id=object.id %}" class="tabs__link">
                                <img src="{% static '/img/collection.svg' %}" alt="" class="tabs__icon">
                                <h4 class="tabs__name">{% translate "Collection" %}</h4>
                                <p class="tabs__count">{{ object.collections.count }}</p>
                            </a>
                        </li>
                        <li class="tabs__item">
                            <a href="{% url 'lists:wishlist' collector_id=object.id %}" class="tabs__link">
                                <img src="{% static 'img/magic-wand-icon.svg' %}" alt="" class="tabs__icon">
                                <h4 class="tabs__name">{% translate "Wishlist" %}</h4>
                                <p class="tabs__count">{{ object.wishlists.count }}</p>
                            </a>
                        </li>
                        <li class="tabs__item">
                            <a href="{% url 'lists:exchange' collector_id=object.id %}" class="tabs__link">
                                <img src="{% static 'img/exchange-icon.svg' %}" alt="" class="tabs__icon">
                                <h4 class="tabs__name">{% translate "Exchange" %}</h4>
                                <p class="tabs__count">{{ object.exchanges.count }}</p>
                            </a>
                        </li>
                        <li class="tabs__item">
                            <a href="{% url 'lists:sale' collector_id=object.id %}" class="tabs__link">
                                <img src="{% static 'img/shopping-icon.svg' %}" alt="" class="tabs__icon">
                                <h4 class="tabs__name">{% translate "Sale" %}</h4>
                                <p class="tabs__count">{{ object.sales.count }}</p>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="collector-user__info-wrapper">
                    {% if object.image %}
                        <img src="{{ object.image.url }}" alt="" class="collector-user__avatar">
                    {% else %}
                        <img src="{% static 'img/avatar.jpg' %}" alt="" class="collector-user__avatar">
                    {% endif %}
                    <div class="collector-user__info">
                        <div class="collector-user__name">
                            <h3 class="collector-user__fullname {% if object.premium %}premium{% endif %}">{{ object.first_name }} {{ object.last_name }}</h3>
                            <p class="collector-user__nick">[{{ object.username }}]</p>
                        </div>
                        <table class="table-info collector-user__table-info">
                            <tr>
                                <td style="width: 90px;" class="table-info__name collector-user__table-name">{% translate "Rating" %}</td>
                                {% if object.rating %}
                                    <td class="table-info__value collector-user__table-value reyting">{{ object.rating }}</td>
                                {% else %}
                                    <td class="table-info__value collector-user__table-value">-</td>
                                {% endif %}                            </tr>
                            <tr>
                                <td class="table-info__name collector-user__table-name">{% translate "Country" %}</td>
                                <td class="table-info__value collector-user__table-value">{{ object.country|default_if_none:'edit in profile' }}</td>
                            </tr>
                            <tr>
                                <td class="table-info__name collector-user__table-name">{% translate "Language" %}</td>
                                <td class="table-info__value collector-user__table-value">{{ object.language|default_if_none:'edit in profile' }}</td>
                            </tr>
                            <tr>
                                <td class="table-info__name collector-user__table-name">{% translate "Birthday" %}</td>
                                <td class="table-info__value collector-user__table-value">{{ object.born_date|default_if_none:'edit in profile' }}</td>
                            </tr>
                        </table>
                        <div class="collector-user__about">
                            <h4 class="collector-user__about-title">{% translate "About user" %}</h4>
                            <p class="collector-user__about-text">{{ object.bio|safe }}
                        </div>
                    </div>
                </div>
                {% if not object.premium %}
                    <div class="collector-user__premium">
                        <h3 class="collector-user__premium-title">{% translate "Premium Subscription" %}</h3>
                        <p class="collector-user__premium-text">{% translate "We give you the opportunity to get all the benefits of a Premium subscription for free for 14 days." %}</p>
                        <a href="#" class="collector-user__premium-link">{% translate "Start Free Trial" %}</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </section>
    <section class="comment-last">
        <div class="container">
            <div class="collector-user__list-title">{% translate "My feedbacks" %}</div>
            <ul class="comment-last__list">
                {% for feedback in feedbacks %}
                    <li class="comment-last__item">
                        <div class="comment-last__img collector-user__table-value reyting">{{ feedback.rating_score }}</div>
                        <div class="comment-last__wrapper">
                            <p class="comment-last__text">{{ feedback.feedback }}</p>
                        </div>
                        <div class="comment-last__author">
                            <p class="comment-last__from">{% translate "To collector" %}</p>
                            <div class="user ">
                                <img src="{% if feedback.collector.image %}{{ feedback.collector.image.url }}{% else %}{% static 'img/avatar.jpg' %}{% endif %}" alt="" class="user__avatar">
                                <div class="user__wrapper">
                                    <h2 class="user__name">{{ feedback.collector.first_name }} {{ feedback.collector.last_name }}</h2>
                                    <p class="user__nick">[{{ feedback.collector.username }}]</p>
                                </div>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock %}