catalog/urls.py
from django.urls import path
from .views import CategoryDetailView, CategoryListView, CassetteBrandListView, CassetteBrandDetail, \
    CassetteCatalogBrandDetailView, TechnologyListView, CassetteDetailView, CassetteCreateView, CassetteUpdateView

app_name = 'catalog'

urlpatterns = [
    path('', CategoryListView.as_view(), name='catalog-list'),
    path('category/<slug>/<brand_slug>/', CassetteCatalogBrandDetailView.as_view(), name='catalog-brand-cassette-list'),
    path('category/<slug>/', CategoryDetailView.as_view(), name='catalog-detail'),
    path('brands/', CassetteBrandListView.as_view(), name='brand-list'),
    path('brands/<slug>/', CassetteBrandDetail.as_view(), name='brand-detail'),
    path('technology/', TechnologyListView.as_view(), name='technologies'),
    path('cassettes/<int:id>/', CassetteDetailView.as_view(), name='cassette'),
    path('cassettes/add/', CassetteCreateView.as_view(), name='cassette_create'),
    path('cassettes/<int:id>/update/', CassetteUpdateView.as_view(), name='cassette_update'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import homepage

app_name = 'core'

urlpatterns = [
    path('', homepage, name='home-page'),
]

kassets/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _

from kassets import settings
from users.views import GoogleSignInView

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n")),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('allauth.socialaccount.urls')),
    path('auth/', include('users.urls')),
    # Если какой-то URL не обнаружится в приложении users —
    # Django пойдёт искать его в django.contrib.auth
    path('auth/', include('django.contrib.auth.urls')),
    path('catalog/', include('catalog.urls')), path('', include('core.urls')),
    path('lists/', include('collection_management.urls'))
)

if settings.DEBUG:
    # import debug_toolbar
    # urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)


admin.site.index_title = _('Site Content Management')
admin.site.site_header = _('Tape Collector Administration')
admin.site.site_title = _('Tape Collector administration')

catalog/models.py
import random
import string
import uuid
from django.db import models
from django.db.models import F, Min, Max
from django.urls import reverse
from django.utils.html import mark_safe
from django.utils.translation import gettext_lazy as _

from pytils.translit import slugify

from core.models import Country
from users.models import Country, User


def title_slugify(model, title):
    slug = slugify(title)
    if model.objects.filter(slug=slug).exists():
        letters = string.ascii_lowercase
        slug = slug + '-' + ''.join(random.choice(letters) for _ in range(3))
    return slug[:50]


class PublishModelManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(is_published=True)


class BaseModel(models.Model):
    """Базовая модель"""
    title = models.CharField(max_length=255, unique=True, verbose_name=_('title'))
    slug = models.SlugField(unique=True, blank=True, verbose_name=_('Url/Slug'))
    is_published = models.BooleanField(default=True, verbose_name=_('Publish'))
    created = models.DateTimeField(auto_now=False, auto_now_add=True,
                                   verbose_name=_('Date of created'))
    updated = models.DateTimeField(auto_now=True, auto_now_add=False,
                                   verbose_name=_('Date of updated'))

    objects = models.Manager()
    published_objects = PublishModelManager()

    class Meta:
        abstract = True
        ordering = ('title', )

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        # self.slug = slugify(self.title)
        self.slug = title_slugify(self.__class__, self.title)
        super().save(*args, **kwargs)


class Category(BaseModel):
    """Модель категории"""
    AUDIO = 'audio'
    VIDEO = 'video'
    CATEGORY_TYPE = ((AUDIO, _('Audio')), (VIDEO, _('Video')),)
    type = models.CharField(max_length=5, choices=CATEGORY_TYPE, default=AUDIO)
    image = models.ImageField(upload_to='category', blank=True)
    logo = models.ImageField(upload_to='category_logo', blank=True)
    description = models.TextField(blank=True)
    brands = models.ManyToManyField('CassetteBrand', related_name='categories', blank=True, verbose_name=_('Brands'))
    is_published_to_home = models.BooleanField(default=False, verbose_name=_('Publish to home page'))
    display_order = models.IntegerField(blank=True, null=True, verbose_name=_('display order'))

    def cassettes_count(self):
        """Считаем количество кассет в категории"""
        return Cassette.objects.filter(brand__categories__slug=self.slug).count()

    class Meta:
        verbose_name = _('Category')
        verbose_name_plural = _('Categories')
        ordering = ('display_order', 'type', 'title')



class CassetteBrand(BaseModel):
    """Модель бренда"""
    country = models.ForeignKey(Country, on_delete=models.CASCADE, blank=True, null=True, verbose_name=_('country'))
    description = models.TextField(blank=True, verbose_name=_('description'))
    image = models.ImageField(upload_to='brands', blank=True, verbose_name=_('image'))

    def cassette_year(self):
        """Вычисляем минимальный и максимальный год кассет в данном бренде"""
        year_period = Cassette.objects.filter(brand=self).aggregate(min=Min('year_release'), max=Max('year_release'))
        return year_period

    def admin_preview(self):
        return mark_safe(
            f'<img src = "{self.image.url}" width = "200"/>')
    admin_preview.short_description = _('image preview')

    def admin_list_preview(self):
        if self.image:
            return mark_safe(
                f'<img src = "{self.image.url}" width = "50"/>')

    admin_list_preview.short_description = _('image')

    class Meta:
        verbose_name = _('brand')
        verbose_name_plural = _('brands')
        ordering = ('title',)




class CassetteModel(BaseModel):
    """Модель модели кассеты"""
    title = models.CharField(max_length=255, unique=False, verbose_name=_('title'))
    brand = models.ForeignKey(CassetteBrand, on_delete=models.PROTECT, verbose_name=_('brand'))
    description = models.TextField(blank=True, verbose_name=_('description'))

    class Meta:
        verbose_name = _('Model')
        verbose_name_plural = _('Models')
        ordering = ('title',)

    def __str__(self):
        return f'{self.title} ({self.brand})'


class CassetteType(BaseModel):
    """Модель типа кассеты"""
    class Meta:
        verbose_name = _('Type')
        verbose_name_plural = _('Types')
        ordering = ('title',)



class CassetteTechnology(BaseModel):
    """Модель технологии кассеты"""
    class Meta:
        verbose_name = _('Technology')
        verbose_name_plural = _('Technologies')
        ordering = ('title',)


class CassetteManufacturer(BaseModel):
    """Модель производителя кассеты"""
    class Meta:
        verbose_name = _('Manufacturer')
        verbose_name_plural = _('Manufacturers')
        ordering = ('title',)


class CassetteSeries(BaseModel):
    """Модель серии кассеты"""
    class Meta:
        verbose_name = _('Series')
        verbose_name_plural = _('Series')
        ordering = ('title',)


class CassetteSort(BaseModel):
    """Модель серии кассеты"""
    class Meta:
        verbose_name = _('sort')
        verbose_name_plural = _('sorts')
        ordering = ('title',)


class CassetteCollection(BaseModel):
    """Модель коллекции"""
    class Meta:
        verbose_name = _('Collection')
        verbose_name_plural = _('Collections')
        ordering = ('title',)


class CassetteTapeLength(models.Model):
    """Модель длины ленты"""
    tape_length = models.CharField(max_length=32,
                                   verbose_name=_('tape length'))

    class Meta:
        verbose_name = _('tape length')
        verbose_name_plural = _('tape lengtes')
        ordering = ('tape_length',)

    def __str__(self):
        return self.tape_length


class CassettePrice(models.Model):
    """Различные варианты цены в зависимости от состояния"""
    poor = models.IntegerField(null=True, blank=True, verbose_name=_('Poor price'))
    good = models.IntegerField(null=True, blank=True, verbose_name=_('Good price'))
    very_good = models.IntegerField(null=True, blank=True, verbose_name=_('Very good price'))
    excellent = models.IntegerField(null=True, blank=True, verbose_name=_('Excellent price'))
    near_mint = models.IntegerField(null=True, blank=True, verbose_name=_('Near mint price'))
    mint = models.IntegerField(null=True, blank=True, verbose_name=_('Mint price'))
    cassette = models.OneToOneField('Cassette', on_delete=models.CASCADE,
                                    related_name='prices',
                                    verbose_name=_('cassette'))

    class Meta:
        verbose_name = _('Price')
        verbose_name_plural = _('Prices')

    def __str__(self):
        return f'{self.cassette} prices'


class Cassette(models.Model):
    """Модель кассеты"""
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False, verbose_name=_('uuid'))
    # user = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name=_('User'))
    coil = models.BooleanField(verbose_name=_('Coil'), null=True, blank=True)
    slim_case = models.BooleanField(verbose_name=_('Slim case'), null=True, blank=True)
    comment = models.TextField(verbose_name=_('Comments'), null=True, blank=True,)
    category = models.ForeignKey(Category, default=1, related_name='cassettes', on_delete=models.PROTECT, verbose_name=_('Category'))
    brand = models.ForeignKey(CassetteBrand, on_delete=models.PROTECT, related_name='cassettes', verbose_name=_('Brand'))
    tape_type = models.ForeignKey(CassetteType, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('tape type'))
    model = models.ForeignKey(CassetteModel, null=True, blank=True,on_delete=models.PROTECT, verbose_name=_('Model'))
    technology = models.ForeignKey(CassetteTechnology, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('technology'))
    manufacturer = models.ForeignKey(CassetteManufacturer, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('manufacturer'))
    series = models.ForeignKey(CassetteSeries, null=True, blank=True, on_delete=models.CASCADE, verbose_name=_('series'))
    sort = models.ForeignKey(CassetteSort, null=True, blank=True, on_delete=models.CASCADE, verbose_name=_('sort'))
    # collection = models.ForeignKey(CassetteCollection, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('Collection'))
    tape_length = models.ForeignKey(CassetteTapeLength, null=True, blank=True, on_delete=models.PROTECT, verbose_name=_('tape Length'))
    year_release = models.IntegerField(null=True, blank=True, verbose_name=_('year Release'))
    country = models.ForeignKey(Country, related_name='country_cassettes', blank=True, null=True, on_delete=models.PROTECT, verbose_name=_('country'))
    markets = models.ManyToManyField(Country,
                                     blank=True,
                                     related_name='markets_cassettes',
                                     verbose_name=_('markets'))
    created = models.DateTimeField(auto_now=False, auto_now_add=True, verbose_name=_('date of comment created'))
    updated = models.DateTimeField(auto_now=True, auto_now_add=False, verbose_name=_('date of comment updated'))
    upload_row = models.IntegerField(null=True, blank=True) # temp field to match data at upload process

    class Meta:
        default_related_name = 'cassettes'
        verbose_name = _('cassette')
        verbose_name_plural = _('cassettes')


    def get_absolute_url(self):
        return reverse('catalog:cassette', kwargs={'id': self.pk})

    def __str__(self):
        if self.brand:
            brand = f' {self.brand.title}'
        else:
            brand = ''
        if self.model:
            model = f' {self.model.title}'
        else:
            model = ''

templates/catalog/brand-detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
    <section class="brands-product section_breadcrumb" id="brands-product">
        <div class="container">
            <ul class="breadcrumb">
                <li class="breadcrumb__item">
                    <a href="/">{% translate "Main" %}</a>
                </li>
                <li class="breadcrumb__item">
                    <a href="{% url 'catalog:brand-list' %}">{% translate "Brands" %}</a>
                </li>
                <li class="breadcrumb__item">{{ brand }}</li>
            </ul>
            <div class="page__head">
                <h2 class="page__title categories-page__title">{{ brand }}</h2>
                <p class="page__descriptions">{{ brand.description }}</p>
            </div>
            <div class="position categories__position">
                <div class="position__wrapper">
                    <div class="position__search">
                        <input type="text" placeholder="{% translate "Search" %}">
                        <button type="submit" class="btn btn_fill">{% translate "Find" %}</button>
                    </div>
                    <div class="position__sorting">
                        <p class="position__sort-text">{% translate "Sort" %}:</p>
                        <div class="position__sort-drop dropdown">
                            <button type="button" class="dropdown__select position__sort-select">{% translate "by Brand" %}</button>
                        </div>
                    </div>
                </div>
                <ul class="sort-by-card">
                    <li class="sort-by-card__item">
                        <a href="#">{% translate "Type of tape" %}</a>
                    </li>
                    <li class="sort-by-card__item">
                        <a href="#">{% translate "Series" %}</a>
                    </li>
                    <li class="sort-by-card__item">
                        <a href="#">{% translate "Tape length" %}</a>
                    </li>
                    <li class="sort-by-card__item">
                        <a href="#">{% translate "Year" %}</a>
                    </li>
                    <li class="sort-by-card__item">
                        <a href="#">{% translate "Country" %}</a>
                    </li>
                    <li class="sort-by-card__item">
                        <a href="#">{% translate "Market" %}</a>
                    </li>
                    <li class="sort-by-card__item">
                        <a href="#">{% translate "Information" %}</a>
                    </li>
                </ul>
                <ul class="sort-by-word">
                    <li class="sort-by-word__item">
                        <a href="#">A</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">B</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">C</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">D</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">E</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">F</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">G</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">H</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">I</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">J</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">K</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">L</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">M</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">N</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">O</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">P</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">Q</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">R</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">S</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">T</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">U</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">V</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">W</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">X</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">Y</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">Z</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">123</a>
                    </li>
                </ul>
                <div class="table-overflow">
                    <table class="table-cust">
                        <tr>
                            <th style="width: 10%;"></th>
                            <th style="width: 10%;">{% translate "Brand" %}</th>
                            <th>{% translate "Model" %}</th>
                            <th>{% translate "Type of tape" %}</th>
                            <th>{% translate "Series" %}</th>
                            <th>{% translate "Tape length" %}</th>
                            <th style="width: 6%;">{% translate "Year" %}</th>
                            <th>{% translate "Country" %}</th>
                            <th style="width: 15%;">{% translate "Market" %}</th>
                            <th>{% translate "Information" %}</th>
                        </tr>
                        {% for cassette in brand.cassettes.all %}
                            <tr>
                                <td>
                                    {% if cassette.images.exists %}
                                        <a href="{% url 'catalog:cassette' id=cassette.id %}">
                                            <img src="{{ cassette.images.first.image.url }}" alt="{{ cassette }}"
                                                 class="product-img" height=70></a>
                                    {% else %}
                                        <a href="{% url 'catalog:cassette' id=cassette.id %}">
                                            <img src="{% static 'img/photo-prev.jpg' %}" alt="{{ cassette }}"
                                                 class="product-img"></a>
                                    {% endif %}
                                </td>
                                <td class="table-cust__medium">{{ brand }}</td>
                                <td>{{ cassette.model.title }}</td>
                                <td>{{ cassette.tape_type.title }}</td>
                                <td>{{ cassette.serie.titles }}</td>
                                <td>{{ cassette.tape_length.tape_length }}</td>
                                <td>{% if cassette.year_release %}{{ cassette.year_release }}{% endif %}</td>
                                <td>{{ cassette.country.title }}</td>
                                <td>{% for market in cassette.markets.all %}<p>{{ market.title }}</p>{% endfor %}</td>
                                <td>
                                    {% comment %}Translators: brand-detail / Требуется уточнение{% endcomment %}
                                    <p class="info correct">{% translate "Clarification required" %}</p>
                                </td>
                            </tr>
                        {% endfor %}

                    </table>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/catalog/category-brand-cassette-list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% block content %}
    <section class="brands-product section_breadcrumb" id="brands-product">
        <div class="container">
            <ul class="breadcrumb">
                <li class="breadcrumb__item">
                    <a href="/">{% translate "Main" %}</a>
                </li>
                <li class="breadcrumb__item">
                    <a href="{% url 'catalog:catalog-list' %}">{% translate "Catalog" %}</a>
                </li>
                <li class="breadcrumb__item">
                    <a href="{% url 'catalog:catalog-detail' slug=category.slug %}">{{ category }}</a>
                </li>
                <li class="breadcrumb__item">{{ brand }}</li>
            </ul>
            <div class="page__head">
                <h2 class="page__title categories-page__title">{{ brand }}</h2>
                <p class="page__descriptions">{{ brand.description }}</p>
            </div>
            <div class="position categories__position">
                <div class="position__wrapper">
                    <div class="position__search">
                        <input type="text" placeholder="Поиск">
                        <button type="submit" class="btn btn_fill">{% translate "Find" %}</button>
                    </div>
                    <div class="position__sorting">
                        <p class="position__sort-text">Сортировать по:</p>
                        <div class="position__sort-drop dropdown">
                            <button type="button" class="dropdown__select position__sort-select">По бренду</button>
                        </div>
                    </div>
                </div>
                <ul class="sort-by-card">
                    <li class="sort-by-card__item">
                        <a href="#">Тип ленты</a>
                    </li>
                    <li class="sort-by-card__item">
                        <a href="#">Серия</a>
                    </li>
                    <li class="sort-by-card__item">
                        <a href="#">Длительность</a>
                    </li>
                    <li class="sort-by-card__item">
                        <a href="#">Год</a>
                    </li>
                    <li class="sort-by-card__item">
                        <a href="#">Страна</a>
                    </li>
                    <li class="sort-by-card__item">
                        <a href="#">Рынок</a>
                    </li>
                    <li class="sort-by-card__item">
                        <a href="#">Информация</a>
                    </li>
                </ul>
                <ul class="sort-by-word">
                    <li class="sort-by-word__item">
                        <a href="#">A</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">B</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">C</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">D</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">E</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">F</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">G</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">H</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">I</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">J</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">K</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">L</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">M</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">N</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">O</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">P</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">Q</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">R</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">S</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">T</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">U</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">V</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">W</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">X</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">Y</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">Z</a>
                    </li>
                    <li class="sort-by-word__item">
                        <a href="#">123</a>
                    </li>
                </ul>
                <div class="table-overflow">
                    <table class="table-cust">
                        <tr>
                            <th style="width: 10%;"></th>
                            <th style="width: 10%;">Бренд</th>
                            <th>Модель</th>
                            <th>Тип ленты</th>
                            <th>Серия</th>
                            <th>Длительность</th>
                            <th style="width: 6%;">Год</th>
                            <th>Страна-производитель</th>
                            <th style="width: 15%;">Рынок</th>
                            <th>Информация</th>
                        </tr>
                        {% for cassette in cassette_list %}
                            <tr>
                                <td>
                                    {% if cassette.images.exists %}
                                        <a href="{% url 'catalog:cassette' id=cassette.id %}">
                                            <img src="{{ cassette.images.first.image.url }}" alt="{{ cassette }}" class="product-img" height=70>
                                        </a>
                                    {% else %}
                                        <a href="{% url 'catalog:cassette' id=cassette.id %}">
                                            <img src="{% static 'img/photo-prev.jpg' %}" alt="{{ cassette }}" class="product-img">
                                        </a>
                                    {% endif %}
                                </td>
                                <td class="table-cust__medium">{{ brand }}</td>
                                <td>{{ cassette.model.title }}</td>
                                <td>{{ cassette.tape_type.title }}</td>
                                <td>{{ cassette.serie.titles }}</td>
                                <td>{{ cassette.tape_length.tape_length }}</td>
                                <td>{% if cassette.year_release %}{{ cassette.year_release }}{% endif %}</td>
                                <td>{{ cassette.country.title }}</td>
                                <td>{% for market in cassette.markets.all %}<p>{{ market.title }}</p>{% endfor %}</td>
                                <td>
                                    <p class="info correct">Требуется уточнение</p>
                                </td>
                            </tr>
                        {% endfor %}

                    </table>
                </div>
            </div>
        </div>
    </section>
{% endblock %}
